"use client";

import { Check, Crown, HeartHandshake, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";

type Plan = "free" | "plus" | "family";
const plans: { id: Plan; name: string; price: string; subtitle: string; features: string[]; tone: string; button: string; icon: typeof Crown }[] = [
  { id: "free", name: "Free", price: "Ücretsiz", subtitle: "Temel takip için", features: ["4 aktif ilaca kadar", "1 tahlil kaydı", "Temel saatlik hatırlatmalar", "Alt bant reklamları"], tone: "border-slate-200 bg-white", button: "border border-slate-300 bg-white text-slate-800", icon: ShieldCheck },
  { id: "plus", name: "Plus", price: "60 TL / ay", subtitle: "Kendin için tam takip", features: ["Sınırsız ilaç ve tahlil kaydı", "Reçete bitiş uyarıları", "İnsülin bölge takibi", "Trend grafikleri ve reklamsız deneyim"], tone: "border-sky-300 bg-gradient-to-br from-sky-50 to-cyan-50", button: "bg-sky-600 text-white hover:bg-sky-700", icon: Crown },
  { id: "family", name: "Aile Plus", price: "100 TL / ay", subtitle: "Kendin ve sevdiklerin için", features: ["Plus’ın tüm avantajları", "3 aile hesabına kadar bağlantı", "Anne, baba veya yakın takip ekranı", "Kaçırılan dozlar için aile uyarıları"], tone: "border-emerald-300 bg-gradient-to-br from-emerald-50 to-teal-50", button: "bg-emerald-600 text-white hover:bg-emerald-700", icon: HeartHandshake },
];

export default function PlansPage() {
  const [selected, setSelected] = useState<Plan>("plus"); const [message, setMessage] = useState("");
  const plan = plans.find((item) => item.id === selected)!;
  const subscribe = () => { if (selected === "free") { setMessage("Free planınız aktif. İstediğiniz zaman Plus paketine geçebilirsiniz."); return; } setMessage(`${plan.name} seçildi. Demo modunda ödeme alınmaz; canlı ödeme sayfası bağlandığında aylık otomatik yenileme onayı burada tamamlanır.`); };
  return <div className="max-w-6xl"><section className="rounded-3xl bg-gradient-to-r from-sky-700 via-sky-600 to-cyan-500 px-6 py-10 text-white sm:px-10"><div className="flex items-start gap-4"><Sparkles className="shrink-0 text-amber-200" size={34} /><div><p className="text-base font-bold text-sky-100">DOZIFY PLUS DENEMESİ</p><h1 className="mt-1 text-3xl font-bold">İlk 3 gün Plus ücretsiz</h1><p className="mt-3 max-w-2xl text-lg leading-7 text-sky-50">Tüm Plus özelliklerini deneyin. Deneme bitiminde seçim yapmazsanız Free planında devam edersiniz.</p></div></div></section>
    <section className="mt-8"><h2 className="text-2xl font-bold text-slate-900">Size uygun planı seçin</h2><p className="mt-2 text-base text-slate-600">Ücretli planlar her ay otomatik yenilenir; istediğiniz zaman Ayarlar&apos;dan yönetebilirsiniz.</p><div className="mt-6 grid gap-5 lg:grid-cols-3">{plans.map((item) => { const Icon = item.icon; const active = selected === item.id; return <button key={item.id} type="button" onClick={() => { setSelected(item.id); setMessage(""); }} className={`relative min-h-80 rounded-3xl border-2 p-6 text-left shadow-card transition ${item.tone} ${active ? "ring-4 ring-sky-200" : "hover:-translate-y-1"}`}>{item.id === "plus" && <span className="absolute -top-3 right-5 rounded-full bg-sky-600 px-3 py-1 text-sm font-bold text-white">En popüler</span>}<Icon className={item.id === "family" ? "text-emerald-600" : item.id === "plus" ? "text-sky-600" : "text-slate-600"} size={32} /><h3 className="mt-4 text-2xl font-bold text-slate-900">{item.name}</h3><p className="mt-1 text-xl font-bold text-slate-800">{item.price}</p><p className="mt-2 text-base text-slate-600">{item.subtitle}</p><ul className="mt-5 space-y-3">{item.features.map((feature) => <li className="flex gap-2 text-base text-slate-700" key={feature}><Check className="mt-0.5 shrink-0 text-emerald-600" size={19} />{feature}</li>)}</ul></button>; })}</div></section>
    <section className={`mt-8 rounded-3xl border-2 p-6 shadow-card ${plan.tone}`}><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-sm font-bold uppercase tracking-wide text-slate-500">Seçili plan</p><h2 className="mt-1 text-2xl font-bold text-slate-900">{plan.name} · {plan.price}</h2><p className="mt-2 max-w-2xl text-base leading-7 text-slate-700">{selected === "family" ? "Plus özelliklerini kendiniz için kullanır, ayrıca anneniz, babanız veya sevdiğiniz bir kişi için takip profili ekleyebilirsiniz." : selected === "plus" ? "Sadece kendi ilaç ve tahlil takibiniz için Plus özelliklerinden yararlanırsınız." : "Ücretsiz kullanımda ilaç ve tahlil kayıtları temel limitlerle sunulur."}</p></div><button onClick={subscribe} className={`h-14 shrink-0 rounded-xl px-6 text-base font-bold ${plan.button}`}>{selected === "free" ? "Free planını kullan" : `${plan.name} satın al`}</button></div>{message && <p className="mt-5 rounded-xl bg-white/80 p-4 text-base text-slate-800">{message}</p>}</section>
  </div>;
}
