"use client";

import { Plus, TrendingUp } from "lucide-react";
import { useState } from "react";
import { demoLabs } from "@/lib/demo-data";
import type { LabResult } from "@/lib/types";
import { LabSpotCard } from "@/components/ui/lab-spot-card";
import { MedicalDisclaimer } from "@/components/ui/disclaimer-modal";

export default function LabsPage() {
  const [results, setResults] = useState<LabResult[]>(demoLabs); const [adding, setAdding] = useState(false);
  const add = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); setResults((old) => [{ id: crypto.randomUUID(), testName: String(f.get("test")), value: Number(f.get("value")), unit: String(f.get("unit")), refMin: Number(f.get("min")), refMax: Number(f.get("max")), testDate: new Date().toISOString().slice(0, 10) }, ...old]); setAdding(false); };
  return <div><MedicalDisclaimer modal /><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-3xl font-bold">Tahlillerim</h1><p className="mt-2 text-lg text-slate-600">Sonuçlarını zaman içindeki değişimiyle gör.</p></div><button onClick={() => setAdding(true)} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-sky-600 px-5 text-base font-bold text-white"><Plus size={20} /> Sonuç ekle</button></div><section className="mt-8 grid gap-5 lg:grid-cols-3">{results.map((result) => <LabSpotCard key={result.id} result={result} />)}</section><section className="mt-8 rounded-2xl bg-white p-6 shadow-card"><div className="flex gap-3"><TrendingUp className="text-sky-600" /><div><h2 className="text-xl font-bold">Trend karşılaştırması</h2><p className="mt-1 text-slate-600">Grafikler Plus üyelikte sınırsız tahlil geçmişiyle kullanılabilir.</p></div></div><div className="mt-6 flex h-32 items-end gap-3 border-b border-slate-200 px-2">{[42, 58, 37, 73, 61, 85].map((height, i) => <div key={i} className="flex-1 rounded-t bg-sky-400" style={{ height: `${height}%` }} />)}</div><div className="mt-2 flex justify-between text-sm text-slate-500"><span>Şubat</span><span>Temmuz</span></div></section>
    {adding && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={add} className="w-full max-w-lg rounded-2xl bg-white p-6"><h2 className="text-2xl font-bold">Tahlil sonucu ekle</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2">Parametre adı<input required name="test" placeholder="Örn. Ferritin" className="mt-1 h-12 w-full rounded-xl border border-slate-300 px-3" /></label><label>Değer<input required name="value" type="number" step="any" className="mt-1 h-12 w-full rounded-xl border border-slate-300 px-3" /></label><label>Birim<input required name="unit" placeholder="ng/mL" className="mt-1 h-12 w-full rounded-xl border border-slate-300 px-3" /></label><label>Alt referans<input required name="min" type="number" step="any" className="mt-1 h-12 w-full rounded-xl border border-slate-300 px-3" /></label><label>Üst referans<input required name="max" type="number" step="any" className="mt-1 h-12 w-full rounded-xl border border-slate-300 px-3" /></label></div><div className="mt-6 flex gap-3"><button type="button" onClick={() => setAdding(false)} className="h-12 flex-1 rounded-xl border border-slate-300 font-bold">Vazgeç</button><button className="h-12 flex-1 rounded-xl bg-sky-600 font-bold text-white">Kaydet</button></div></form></div>}
  </div>;
}
