"use client";

import { Plus, Search, TrendingUp } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { DeleteConfirmModal } from "@/components/ui/delete-confirm-modal";
import { LabSpotCard, labStatus } from "@/components/ui/lab-spot-card";
import { useProfile } from "@/components/profile-provider";
import { demoLabs } from "@/lib/demo-data";
import { labCatalog, type LabDefinition } from "@/lib/lab-catalog";
import type { LabResult } from "@/lib/types";

export default function LabsPage() {
  const { activeProfile } = useProfile();
  const [results, setResults] = useState<LabResult[]>(demoLabs); const [adding, setAdding] = useState(false); const [deleteId, setDeleteId] = useState<string>(); const [loadedProfileId, setLoadedProfileId] = useState("");
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<LabDefinition>(); const [value, setValue] = useState(""); const [refMin, setRefMin] = useState(0); const [refMax, setRefMax] = useState(0); const [editRange, setEditRange] = useState(false);
  useEffect(() => { const saved = localStorage.getItem(`dozify-demo-labs-${activeProfile.id}`); setResults(saved ? JSON.parse(saved) : activeProfile.id === "emir" ? demoLabs : []); setLoadedProfileId(activeProfile.id); }, [activeProfile.id]);
  useEffect(() => { if (loadedProfileId === activeProfile.id) localStorage.setItem(`dozify-demo-labs-${activeProfile.id}`, JSON.stringify(results)); }, [activeProfile.id, loadedProfileId, results]);
  const suggestions = useMemo(() => { const search = query.trim().toLocaleLowerCase("tr-TR"); return search.length < 2 ? [] : labCatalog.filter((test) => [test.name, ...test.aliases].some((term) => term.toLocaleLowerCase("tr-TR").includes(search))).slice(0, 6); }, [query]);
  const chooseTest = (test: LabDefinition) => { setSelected(test); setQuery(test.name); setRefMin(test.refMin); setRefMax(test.refMax); setEditRange(false); };
  const preview: LabResult | undefined = selected && value !== "" ? { id: "preview", testName: selected.name, value: Number(value), unit: selected.unit, refMin, refMax, testDate: "" } : undefined;
  const add = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected || !value) return; setResults((old) => [{ ...preview!, id: crypto.randomUUID(), testDate: new Date().toISOString().slice(0, 10) }, ...old]); setAdding(false); setQuery(""); setValue(""); setSelected(undefined); };
  const deleting = results.find((result) => result.id === deleteId);
  const chartResults = results.slice(0, 6).reverse();
  const chartMaximum = Math.max(...chartResults.map((result) => result.value), 1);
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-3xl font-bold">{activeProfile.name} · Tahliller</h1><p className="mt-2 text-lg text-slate-600">Sonuçlarını zaman içindeki değişimiyle gör.</p></div><button onClick={() => setAdding(true)} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-sky-600 px-5 text-base font-bold text-white"><Plus size={20} /> Sonuç ekle</button></div><section className="mt-8 grid gap-5 lg:grid-cols-3">{results.map((result) => <LabSpotCard key={result.id} result={result} onDelete={() => setDeleteId(result.id)} />)}{results.length === 0 && <p className="rounded-2xl bg-white p-6 text-base text-slate-600 shadow-card">Bu profil için henüz tahlil sonucu yok.</p>}</section><section className="mt-8 rounded-2xl bg-white p-6 shadow-card"><div className="flex gap-3"><TrendingUp className="text-sky-600" /><div><h2 className="text-xl font-bold">Trend karşılaştırması</h2><p className="mt-1 text-slate-600">Kaydedilen sonuçlarınızdan oluşan görsel karşılaştırma.</p></div></div>{chartResults.length > 0 ? <><div className="mt-6 flex h-32 items-end gap-3 border-b border-slate-200 px-2">{chartResults.map((result) => <div key={result.id} className="flex flex-1 flex-col justify-end"><div className="rounded-t bg-sky-400" style={{ height: `${Math.max(15, Math.round((result.value / chartMaximum) * 100))}%` }} title={`${result.testName}: ${result.value} ${result.unit}`} /></div>)}</div><div className="mt-2 flex justify-between gap-2 overflow-hidden text-xs text-slate-500">{chartResults.map((result) => <span className="truncate" key={result.id}>{result.testName}</span>)}</div></> : <p className="mt-5 text-base text-slate-500">Grafiği görmek için bu profile tahlil sonucu ekleyin.</p>}</section>
    <aside className="mt-6 rounded-xl border border-sky-100 bg-sky-50 p-4 text-sm leading-6 text-sky-950">Değerler üniversite hastaneleri ve evrensel sınırlar üzerinden değerlendirilir. Doğru aralıkları tahlil sonuç belgenizle karşılaştırmanız daha doğrudur.</aside>
    {adding && <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/40 p-4"><form onSubmit={add} className="mx-auto my-4 w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-2xl font-bold">Tahlil sonucu ekle</h2><p className="mt-1 text-base text-slate-600">Testi seç, sadece kendi sonucunu gir.</p><label className="mt-5 block text-base font-semibold text-slate-700">Tahlil adı<div className="relative mt-1"><Search className="pointer-events-none absolute left-3 top-3 text-slate-400" size={21} /><input required value={query} onChange={(event) => { setQuery(event.target.value); setSelected(undefined); }} placeholder="Örn. Glu..." className="h-12 w-full rounded-xl border border-slate-300 py-2 pl-11 pr-3 text-base" autoComplete="off" />{suggestions.length > 0 && <div className="absolute z-10 mt-1 w-full overflow-hidden rounded-xl border border-sky-100 bg-white shadow-lg">{suggestions.map((test) => <button type="button" onClick={() => chooseTest(test)} key={test.id} className="flex min-h-12 w-full items-center justify-between px-3 text-left text-base hover:bg-sky-50"><span>{test.name}</span><span className="text-sm text-slate-500">{test.refMin}–{test.refMax} {test.unit}</span></button>)}</div>}</div></label>
      {selected && <><label className="mt-5 block text-base font-semibold text-slate-700">Sonucunuz ({selected.unit})<input required autoFocus value={value} onChange={(event) => setValue(event.target.value)} type="number" step="any" className="mt-1 h-12 w-full rounded-xl border border-slate-300 px-3 text-base" placeholder="Örn. 115" /></label><button type="button" onClick={() => setEditRange((open) => !open)} className="mt-4 min-h-12 text-base font-bold text-sky-700 underline">Referans aralığını düzenle</button>{editRange && <div className="mt-3 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3"><label className="text-sm font-semibold">Alt sınır<input value={refMin} onChange={(event) => setRefMin(Number(event.target.value))} type="number" step="any" className="mt-1 h-12 w-full rounded-xl border border-slate-300 px-3" /></label><label className="text-sm font-semibold">Üst sınır<input value={refMax} onChange={(event) => setRefMax(Number(event.target.value))} type="number" step="any" className="mt-1 h-12 w-full rounded-xl border border-slate-300 px-3" /></label></div>}{preview && <p className={`mt-4 rounded-xl p-3 text-base font-bold ${labStatus(preview) === "normal" ? "bg-emerald-100 text-emerald-800" : labStatus(preview) === "low" ? "bg-amber-100 text-amber-900" : "bg-red-100 text-red-800"}`}>{labStatus(preview) === "normal" ? "Normal" : labStatus(preview) === "low" ? "Düşük" : "Yüksek"} · Referans: {refMin}–{refMax} {selected.unit}</p>}</>}
      <div className="mt-6 flex gap-3"><button type="button" onClick={() => setAdding(false)} className="h-12 flex-1 rounded-xl border border-slate-300 font-bold">Vazgeç</button><button disabled={!preview} className="h-12 flex-1 rounded-xl bg-sky-600 font-bold text-white disabled:cursor-not-allowed disabled:bg-slate-300">Kaydet</button></div></form></div>}
    {deleting && <DeleteConfirmModal title="Tahlil sonucu silinsin mi?" description={`${deleting.testName} sonucu kalıcı olarak kaldırılacak.`} onCancel={() => setDeleteId(undefined)} onConfirm={() => { setResults((items) => items.filter((item) => item.id !== deleteId)); setDeleteId(undefined); }} />}
  </div>;
}
