export type LabDefinition = { id: string; name: string; aliases: string[]; unit: string; refMin: number; refMax: number; category: string };

// Default adult reference ranges for demo/education only. Method, age, sex and laboratory can change ranges.
const lab = (id: string, name: string, aliases: string[], unit: string, refMin: number, refMax: number, category: string): LabDefinition => ({ id, name, aliases, unit, refMin, refMax, category });

export const labCatalog: LabDefinition[] = [
  // Hemogram
  lab("wbc", "WBC (Lökosit)", ["wbc", "lökosit", "beyaz kan"], "10³/µL", 4, 10, "Hemogram"),
  lab("rbc", "RBC (Eritrosit)", ["rbc", "eritrosit"], "10⁶/µL", 4.2, 5.9, "Hemogram"),
  lab("hemoglobin", "Hemoglobin (Hb)", ["hb", "hgb", "hemoglobin"], "g/dL", 12, 17.5, "Hemogram"),
  lab("hematocrit", "Hematokrit (HCT)", ["hct", "hematokrit"], "%", 36, 52, "Hemogram"),
  lab("mcv", "MCV", ["mcv"], "fL", 80, 100, "Hemogram"),
  lab("mch", "MCH", ["mch"], "pg", 27, 33, "Hemogram"),
  lab("mchc", "MCHC", ["mchc"], "g/dL", 32, 36, "Hemogram"),
  lab("rdw", "RDW", ["rdw"], "%", 11.5, 14.5, "Hemogram"),
  lab("plt", "PLT (Trombosit)", ["plt", "platelet", "trombosit"], "10³/µL", 150, 450, "Hemogram"),
  lab("neutrophil", "Nötrofil", ["nötrofil", "neu"], "%", 40, 75, "Hemogram"),
  lab("lymphocyte", "Lenfosit", ["lenfosit", "lym"], "%", 20, 45, "Hemogram"),
  lab("monocyte", "Monosit", ["monosit", "mono"], "%", 2, 10, "Hemogram"),
  lab("eosinophil", "Eozinofil", ["eozinofil", "eos"], "%", 0, 6, "Hemogram"),
  lab("basophil", "Bazofil", ["bazofil", "baso"], "%", 0, 2, "Hemogram"),
  // Biyokimya / böbrek
  lab("glucose", "Açlık Kan Şekeri (Glukoz)", ["glukoz", "glu", "açlık şekeri"], "mg/dL", 70, 100, "Biyokimya"),
  lab("hba1c", "HbA1c", ["hba1c", "şeker"], "%", 4, 5.6, "Biyokimya"),
  lab("urea", "Üre", ["üre", "urea", "bun"], "mg/dL", 15, 45, "Biyokimya"),
  lab("creatinine", "Kreatinin", ["kreatinin", "creatinine"], "mg/dL", 0.6, 1.3, "Biyokimya"),
  lab("egfr", "eGFR", ["egfr", "gfr"], "mL/dk/1.73m²", 90, 120, "Biyokimya"),
  lab("uric-acid", "Ürik Asit", ["ürik asit", "uric acid"], "mg/dL", 3.5, 7.2, "Biyokimya"),
  lab("sodium", "Sodyum (Na)", ["sodyum", "na"], "mmol/L", 135, 145, "Biyokimya"),
  lab("potassium", "Potasyum (K)", ["potasyum", "k"], "mmol/L", 3.5, 5.1, "Biyokimya"),
  lab("calcium", "Kalsiyum", ["kalsiyum", "ca"], "mg/dL", 8.6, 10.2, "Biyokimya"),
  lab("magnesium", "Magnezyum", ["magnezyum", "mg"], "mg/dL", 1.6, 2.6, "Biyokimya"),
  lab("phosphorus", "Fosfor", ["fosfor", "p"], "mg/dL", 2.5, 4.5, "Biyokimya"),
  lab("crp", "C-Reaktif Protein (CRP)", ["crp", "c reaktif protein"], "mg/L", 0, 5, "Biyokimya"),
  // Karaciğer
  lab("alt", "ALT (SGPT)", ["alt", "sgpt"], "U/L", 0, 41, "Karaciğer"),
  lab("ast", "AST (SGOT)", ["ast", "sgot"], "U/L", 0, 40, "Karaciğer"),
  lab("alp", "Alkalen Fosfataz (ALP)", ["alp", "alkalen fosfataz"], "U/L", 44, 147, "Karaciğer"),
  lab("ggt", "GGT", ["ggt", "gama glutamil"], "U/L", 9, 48, "Karaciğer"),
  lab("bilirubin-total", "Total Bilirubin", ["total bilirubin", "bilirubin"], "mg/dL", 0.2, 1.2, "Karaciğer"),
  lab("bilirubin-direct", "Direkt Bilirubin", ["direkt bilirubin"], "mg/dL", 0, 0.3, "Karaciğer"),
  lab("albumin", "Albümin", ["albumin", "albümin"], "g/dL", 3.5, 5.2, "Karaciğer"),
  lab("total-protein", "Total Protein", ["total protein"], "g/dL", 6.4, 8.3, "Karaciğer"),
  lab("ldh", "LDH", ["ldh"], "U/L", 140, 280, "Karaciğer"),
  // Lipid
  lab("total-cholesterol", "Total Kolesterol", ["kolesterol", "total kolesterol"], "mg/dL", 0, 200, "Lipid"),
  lab("ldl", "LDL Kolesterol", ["ldl"], "mg/dL", 0, 130, "Lipid"),
  lab("hdl", "HDL Kolesterol", ["hdl"], "mg/dL", 40, 100, "Lipid"),
  lab("triglyceride", "Trigliserid", ["trigliserid", "tg"], "mg/dL", 0, 150, "Lipid"),
  // Tiroid / hormon
  lab("tsh", "TSH", ["tsh", "tiroid"], "mIU/L", 0.4, 4, "Tiroid ve Hormon"),
  lab("ft3", "Serbest T3 (fT3)", ["ft3", "serbest t3"], "pg/mL", 2, 4.4, "Tiroid ve Hormon"),
  lab("ft4", "Serbest T4 (fT4)", ["ft4", "serbest t4"], "ng/dL", 0.8, 1.8, "Tiroid ve Hormon"),
  lab("anti-tpo", "Anti-TPO", ["anti tpo", "antitpo"], "IU/mL", 0, 35, "Tiroid ve Hormon"),
  lab("anti-tg", "Anti-Tiroglobulin", ["anti tg", "antitg"], "IU/mL", 0, 115, "Tiroid ve Hormon"),
  lab("insulin", "İnsülin", ["insülin", "insulin"], "µIU/mL", 2.6, 24.9, "Tiroid ve Hormon"),
  lab("cortisol", "Kortizol (sabah)", ["kortizol", "cortisol"], "µg/dL", 5, 25, "Tiroid ve Hormon"),
  lab("prolactin", "Prolaktin", ["prolaktin"], "ng/mL", 4, 23, "Tiroid ve Hormon"),
  lab("fsh", "FSH", ["fsh"], "mIU/mL", 1.5, 12.4, "Tiroid ve Hormon"),
  lab("lh", "LH", ["lh"], "mIU/mL", 1.7, 8.6, "Tiroid ve Hormon"),
  lab("testosterone", "Total Testosteron", ["testosteron"], "ng/dL", 300, 1000, "Tiroid ve Hormon"),
  // Vitamin / demir
  lab("ferritin", "Ferritin", ["ferritin", "demir deposu"], "ng/mL", 15, 150, "Vitamin ve Demir"),
  lab("iron", "Serum Demiri", ["demir", "serum demiri"], "µg/dL", 60, 170, "Vitamin ve Demir"),
  lab("tibc", "Total Demir Bağlama Kapasitesi", ["tibc", "demir bağlama"], "µg/dL", 250, 450, "Vitamin ve Demir"),
  lab("transferrin", "Transferrin", ["transferrin"], "mg/dL", 200, 360, "Vitamin ve Demir"),
  lab("b12", "B12 Vitamini", ["b12", "vitamin b12"], "pg/mL", 197, 771, "Vitamin ve Demir"),
  lab("folate", "Folat", ["folat", "folik asit"], "ng/mL", 4, 20, "Vitamin ve Demir"),
  lab("vitamin-d", "25-OH Vitamin D", ["d vitamini", "vitamin d"], "ng/mL", 20, 100, "Vitamin ve Demir"),
  lab("zinc", "Çinko", ["çinko", "zinc"], "µg/dL", 70, 120, "Vitamin ve Demir"),
  // İdrar ve pıhtılaşma
  lab("urine-ph", "İdrar pH", ["idrar ph", "ph"], "pH", 5, 8, "İdrar"),
  lab("urine-density", "İdrar Dansitesi", ["dansite", "özgül ağırlık"], "", 1.005, 1.03, "İdrar"),
  lab("urine-protein", "İdrar Proteini", ["idrar protein", "protein"], "mg/dL", 0, 15, "İdrar"),
  lab("urine-glucose", "İdrar Glukozu", ["idrar glukoz", "idrar şekeri"], "mg/dL", 0, 15, "İdrar"),
  lab("urine-rbc", "İdrar Eritrosit", ["idrar eritrosit", "idrar rbc"], "/HPF", 0, 2, "İdrar"),
  lab("urine-wbc", "İdrar Lökosit", ["idrar lökosit", "idrar wbc"], "/HPF", 0, 5, "İdrar"),
  lab("inr", "INR", ["inr"], "", 0.8, 1.2, "Pıhtılaşma"),
  lab("pt", "Protrombin Zamanı (PT)", ["pt", "protrombin"], "sn", 11, 13.5, "Pıhtılaşma"),
  lab("aptt", "aPTT", ["aptt"], "sn", 25, 35, "Pıhtılaşma"),
];
