"use client";

import { CheckCircle2, Copy, HeartHandshake, KeyRound, ShieldAlert, UserRoundCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { useProfile } from "@/components/profile-provider";

export default function FamilyPage() {
  const { profiles, activeProfile, selfProfile, setActiveProfileId, createPersonalCode, linkFamilyCode } = useProfile();
  const [copied, setCopied] = useState(false); const [linkResult, setLinkResult] = useState("");
  const copyCode = async () => { const profile = createPersonalCode(); await navigator.clipboard.writeText(profile.familyCode); setCopied(true); };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = new FormData(event.currentTarget); const result = linkFamilyCode(String(values.get("code")), String(values.get("relation"))); setLinkResult(result.message); if (result.ok) event.currentTarget.reset(); };
  return <div><div><h1 className="text-3xl font-bold">Aile yönetimi</h1><p className="mt-2 text-lg text-slate-600">Aile koduyla bir yakının hesabını güvenli biçimde takip et.</p></div>
    <section className="mt-8 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl bg-white p-6 shadow-card"><KeyRound className="text-sky-600" size={32} /><h2 className="mt-3 text-2xl font-bold">Kişisel aile kodun</h2><p className="mt-2 leading-7 text-slate-600">Bu kod, hesabının aile kimliğidir. Sadece güvendiğin yakınlarınla paylaş.</p><div className="mt-5 flex items-center justify-between gap-3 rounded-xl bg-sky-50 p-4"><span className="font-mono text-3xl font-bold tracking-[0.2em] text-sky-950">{selfProfile.familyCode}</span><button onClick={copyCode} className="grid h-12 w-12 place-items-center rounded-xl bg-white text-sky-700 shadow-sm" aria-label="Aile kodunu kopyala">{copied ? <CheckCircle2 /> : <Copy />}</button></div></article>
      <form onSubmit={submit} className="rounded-2xl bg-white p-6 shadow-card"><HeartHandshake className="text-emerald-600" size={32} /><h2 className="mt-3 text-2xl font-bold">Aile hesabı bağla</h2><p className="mt-2 leading-7 text-slate-600">Babanın veya başka bir yakınının 6 haneli aile kodunu girerek takip profilini ekle.</p><label className="mt-4 block text-base font-semibold">Aile kodu<input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required placeholder="000000" className="mt-1 h-12 w-full rounded-xl border border-slate-300 px-3 font-mono text-xl tracking-[0.25em]" /></label><label className="mt-4 block text-base font-semibold">Yakınlık<select name="relation" className="mt-1 h-12 w-full rounded-xl border border-slate-300 px-3 text-base"><option>Baba</option><option>Anne</option><option>Çocuk</option><option>Kardeş</option><option>Diğer</option></select></label><button className="mt-5 h-12 w-full rounded-xl bg-sky-600 text-base font-bold text-white">Hesabı bağla</button>{linkResult && <p className="mt-3 rounded-xl bg-sky-50 p-3 text-sm leading-6 text-sky-900">{linkResult}</p>}</form></section>
    <section className="mt-8"><h2 className="text-2xl font-bold">Bağlı hesaplar</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{profiles.map((profile) => <article key={profile.id} className={`rounded-2xl border-2 bg-white p-5 shadow-card ${activeProfile.id === profile.id ? "border-sky-500" : "border-transparent"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xl font-bold text-slate-900">{profile.name}</p><p className="mt-1 text-base text-slate-600">{profile.relation} · {profile.access === "managed" ? "Takip edilen hesap" : "Kendi hesabın"}</p></div>{activeProfile.id === profile.id && <span className="inline-flex min-h-8 items-center rounded-full bg-sky-100 px-3 text-sm font-bold text-sky-800">Aktif</span>}</div><button onClick={() => setActiveProfileId(profile.id)} className="mt-5 h-12 w-full rounded-xl border border-sky-200 text-base font-bold text-sky-800 hover:bg-sky-50">Bu profili aç</button></article>)}</div></section>
    {activeProfile.access === "managed" && <section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-6"><UserRoundCheck className="text-amber-700" size={32} /><h2 className="mt-3 text-xl font-bold text-amber-950">{activeProfile.name} hesabını düzenliyorsunuz</h2><p className="mt-2 leading-7 text-amber-950">Bu ekranda {activeProfile.name} için ilaç, tahlil ve hatırlatıcı bilgilerini düzenliyorsunuz. Bilgileri yalnızca ilgili kişinin bilgisi ve izniyle güncelleyin.</p></section>}
    <section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-6"><ShieldAlert className="text-amber-700" size={32} /><h2 className="mt-4 text-xl font-bold text-amber-950">Etik kullanım hatırlatması</h2><p className="mt-3 leading-7 text-amber-950">Uygulamadaki ilaç onayları bireyin öz beyanına dayanır. Sistem fiziksel kullanımı garanti edemez.</p></section>
  </div>;
}
