"use client";

import { CheckCircle2, Copy, HeartHandshake, ShieldAlert } from "lucide-react";
import { useState } from "react";

export default function FamilyPage() {
  const [link, setLink] = useState(""); const [copied, setCopied] = useState(false);
  const createInvite = () => { const token = crypto.randomUUID(); setLink(`${window.location.origin}/baglan?token=${token}`); setCopied(false); };
  const copy = async () => { await navigator.clipboard.writeText(link); setCopied(true); };
  return <div><h1 className="text-3xl font-bold">Aile ve bakım takibi</h1><p className="mt-2 text-lg text-slate-600">Yakınlarınla doz durumunu güvenli biçimde paylaş.</p><div className="mt-8 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl bg-white p-6 shadow-card"><HeartHandshake className="text-sky-600" size={32} /><h2 className="mt-4 text-2xl font-bold">Yakınını bağla</h2><p className="mt-2 leading-7 text-slate-600">Tek kullanımlık davet bağlantısı oluştur. Bağlantı kabul edildiğinde bakım veren doz durumunu görebilir.</p>{link ? <div className="mt-5"><label className="text-sm font-semibold text-slate-600">Davet bağlantısı</label><div className="mt-1 flex gap-2"><input readOnly value={link} className="h-12 min-w-0 flex-1 rounded-xl border border-slate-300 px-3 text-sm" /><button onClick={copy} className="grid h-12 w-12 place-items-center rounded-xl bg-sky-600 text-white" aria-label="Bağlantıyı kopyala">{copied ? <CheckCircle2 /> : <Copy />}</button></div><p className="mt-2 text-sm text-slate-500">Bu bağlantıyı üretimde Supabase&apos;te tek kullanımlık olarak kaydedin.</p></div> : <button onClick={createInvite} className="mt-6 h-12 rounded-xl bg-sky-600 px-5 text-base font-bold text-white">Davet bağlantısı oluştur</button>}</section><section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><ShieldAlert className="text-amber-700" size={32} /><h2 className="mt-4 text-xl font-bold text-amber-950">Etik kullanım hatırlatması</h2><p className="mt-3 leading-7 text-amber-950">Uygulamadaki ilaç onayları bireyin öz beyanına dayanmaktadır. Sistem fiziksel kullanımı garanti edemez. Haftalık ilaç kutularını fiziken kontrol etmeniz önerilir.</p></section></div><section className="mt-8 rounded-2xl bg-white p-6 shadow-card"><h2 className="text-xl font-bold">Canlı takip akışı</h2><div className="mt-4 flex items-center gap-3 rounded-xl bg-emerald-50 p-4"><CheckCircle2 className="shrink-0 text-emerald-600" /><p className="text-base text-emerald-950"><strong>Annem</strong> tansiyon ilacını aldı. <span className="text-sm">09:04</span></p></div></section></div>;
}
