"use client";

import { CheckCircle2, Copy, HeartHandshake, Plus, ShieldAlert, UserRoundPlus } from "lucide-react";
import { FormEvent, useState } from "react";
import { useProfile } from "@/components/profile-provider";

export default function FamilyPage() {
  const { profiles, activeProfile, setActiveProfileId, addProfile } = useProfile();
  const [adding, setAdding] = useState(false); const [copied, setCopied] = useState("");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); addProfile(String(data.get("name")).trim(), String(data.get("relation"))); setAdding(false); };
  const copyCode = async (code: string) => { await navigator.clipboard.writeText(code); setCopied(code); };
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-3xl font-bold">Aile yönetimi</h1><p className="mt-2 text-lg text-slate-600">Her aile üyesi için ayrı ilaç ve tahlil takibi yap.</p></div><button onClick={() => setAdding(true)} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-sky-600 px-5 text-base font-bold text-white"><UserRoundPlus size={20} /> Profil ekle</button></div>
    <section className="mt-8 grid gap-4 md:grid-cols-2">{profiles.map((profile) => <article key={profile.id} className={`rounded-2xl border-2 bg-white p-5 shadow-card ${activeProfile.id === profile.id ? "border-sky-500" : "border-transparent"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xl font-bold text-slate-900">{profile.name}</p><p className="mt-1 text-base text-slate-600">{profile.relation}</p></div>{activeProfile.id === profile.id && <span className="inline-flex min-h-8 items-center rounded-full bg-sky-100 px-3 text-sm font-bold text-sky-800">Aktif</span>}</div>{profile.id !== "emir" && <div className="mt-5 rounded-xl bg-sky-50 p-3"><p className="text-sm font-semibold text-sky-900">Aile davet kodu</p><div className="mt-1 flex items-center justify-between gap-3"><span className="font-mono text-2xl font-bold tracking-[0.2em] text-sky-950">{profile.inviteCode}</span><button onClick={() => copyCode(profile.inviteCode)} className="grid h-12 w-12 place-items-center rounded-xl bg-white text-sky-700 shadow-sm" aria-label="Davet kodunu kopyala">{copied === profile.inviteCode ? <CheckCircle2 /> : <Copy />}</button></div></div>}<button onClick={() => setActiveProfileId(profile.id)} className="mt-5 h-12 w-full rounded-xl border border-sky-200 text-base font-bold text-sky-800 hover:bg-sky-50">Bu profile geç</button></article>)}</section>
    <section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-6"><ShieldAlert className="text-amber-700" size={32} /><h2 className="mt-4 text-xl font-bold text-amber-950">Etik kullanım hatırlatması</h2><p className="mt-3 leading-7 text-amber-950">Uygulamadaki ilaç onayları bireyin öz beyanına dayanmaktadır. Sistem fiziksel kullanımı garanti edemez. Haftalık ilaç kutularını fiziken kontrol etmeniz önerilir.</p></section>
    {adding && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><HeartHandshake className="text-sky-600" size={32} /><h2 className="mt-3 text-2xl font-bold">Aile profili oluştur</h2><label className="mt-5 block text-base font-semibold">Profil adı<input required name="name" placeholder="Örn. Çocuğum" className="mt-1 h-12 w-full rounded-xl border border-slate-300 px-3 text-base" /></label><label className="mt-4 block text-base font-semibold">Yakınlık<select required name="relation" className="mt-1 h-12 w-full rounded-xl border border-slate-300 px-3 text-base"><option value="Anne">Anne</option><option value="Baba">Baba</option><option value="Çocuk">Çocuk</option><option value="Kardeş">Kardeş</option><option value="Diğer">Diğer</option></select></label><p className="mt-4 rounded-xl bg-sky-50 p-3 text-sm leading-6 text-sky-900">Profil oluşturulduğunda 6 haneli bir mock aile davet kodu otomatik atanır.</p><div className="mt-6 flex gap-3"><button type="button" onClick={() => setAdding(false)} className="h-12 flex-1 rounded-xl border border-slate-300 font-bold">Vazgeç</button><button className="h-12 flex-1 rounded-xl bg-sky-600 font-bold text-white">Profili oluştur</button></div></form></div>}
  </div>;
}
